### ISSUE TITLE
com.flutterwave.raveandroid.card.CardFragment$ExpiryWatcher.afterTextChanged

### ISSUE THREAD

**Issue by JasminPambhar** [Flutterwave/AndroidSDK#296]
Fatal Exception: java.lang.NumberFormatException: Invalid int: "1 "
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:410)
       at java.lang.Integer.parseInt(Integer.java:367)
       at java.lang.Integer.parseInt(Integer.java:334)
       at com.flutterwave.raveandroid.card.CardFragment$ExpiryWatcher.afterTextChanged(CardFragment.java:814)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:8340)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:10531)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1061)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:573)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:314)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:503)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:304)
       at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:48)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:693)
       at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:204)
       at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:191)
       at android.view.inputmethod.InputConnectionWrapper.commitText(InputConnectionWrapper.java:82)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:286)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5765)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by showdpro** [comment]
Try to use BigDecimal conversion in your code. I had this issue before but was able to resolve this way. Hope it helps

**Comment by codeismail-waver** [comment]
Hello @JasminPambhar this [pr](https://github.com/Flutterwave/AndroidSDK/pull/302) has been merged for this issue. kindly use v2.2.1 . if the issue persist kindly provide a detailed step to reproduce it.
